# need this for netCDF
FROM osgeo/gdal:ubuntu-full-latest 

# Make a developer user so as not to always be root
RUN useradd -ms /bin/bash develop
RUN echo "develop   ALL=(ALL:ALL) ALL" >> /etc/sudoers
USER develop

# Pyenv dependencies
USER root
RUN apt-get update
RUN apt-get install -y --fix-missing build-essential libssl-dev zlib1g-dev libbz2-dev \
libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev \
xz-utils tk-dev libffi-dev liblzma-dev python-openssl git

# Pyenv may be overkill - was trying it in order to help with gdal install
# but never got it to work. Decided to use a separate image with gdal support
USER develop
ENV HOME=/home/develop
RUN git clone https://github.com/pyenv/pyenv.git $HOME/.pyenv
ENV PYENV_ROOT=$HOME/.pyenv
ENV PATH=$PYENV_ROOT/shims:$PYENV_ROOT/bin:$PATH
RUN git clone https://github.com/pyenv/pyenv-virtualenv.git $(pyenv root)/plugins/pyenv-virtualenv
RUN pyenv install 3.8.6
RUN pyenv global 3.8.6
RUN pyenv rehash
RUN python --version
RUN pip install -U pip pipenv
COPY requirements.txt .
RUN pip install -r requirements.txt

# or use this if not wanting to use requirements.txt...
# RUN pip install matplotlib numpy pandas bokeh netCDF4 commentjson
# RUN pip install ipython
# # Bug with ipython 7.19.0, so need to downgrade and pin jedi verison
# # # https://github.com/ipython/ipython/issues/12740
# RUN pip install jedi==0.17.2

WORKDIR /work

#CMD bokeh serve scripts


# docker build --target dvmdostem-mapping-support --tag dvmdostem-mapping-support:0.0.1 .
#INCATALOG=
# docker run -it --rm -p 5006:5006 --volume $(pwd):/work --volume $INCATALOG:/data/dvmdostem-input-catalog dvmdostem-mapping-support:0.0.1























#-------------------
# FROM perrygeo/gdal-base:latest as builder
# # Python dependencies that require compilation
# COPY requirements.txt .
# RUN python -m pip install cython numpy -c requirements.txt
# RUN python -m pip install --no-binary fiona,rasterio,shapely -r requirements.txt
# RUN pip uninstall cython --yes

# # ------ Second stage
# # Start from a clean image
# FROM python:3.8-slim-buster as final

# # Install some required runtime libraries from apt
# RUN apt-get update \
#     && apt-get install --yes --no-install-recommends \
#        libfreexl1 libxml2 libffi-dev\
#     && rm -rf /var/lib/apt/lists/*

# # Install the previously-built shared libaries from the builder image
# COPY --from=builder /usr/local/* /usr/local/
# RUN ldconfig -v

#FROM osgeo/gdal:ubuntu-small-latest