FROM ubuntu:focal

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update

# general dev tools
RUN apt-get install -y build-essential git gdb gdb-server doxygen

# dvmdostem dependencies
RUN apt-get install -y libjsoncpp-dev libnetcdf-dev libboost-all-dev libreadline-dev liblapacke liblapacke-dev

