#############################################################################
# Makefile for building: model
# Generated by qmake (1.07a) (Qt 3.3.6) on: Thu Apr 26 09:26:32 2012
# Project:  model.pro
# Template: app
# Command: $(QMAKE) -o Makefile model.pro
#############################################################################

####### Compiler, tools and options

CC       = gcc
CXX      = g++
LEX      = flex
YACC     = yacc
CFLAGS   = -pipe -Wall -W -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic  -DQT_NO_DEBUG -DQT_SHARED -DQT_THREAD_SUPPORT
CXXFLAGS = -pipe -Wall -W -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic  -DQT_NO_DEBUG -DQT_SHARED -DQT_THREAD_SUPPORT
LEXFLAGS = 
YACCFLAGS= -d
INCPATH  = -I/usr/lib64/qt-3.3/mkspecs/default -I. -I. -Isrc/assembler -Isrc/runmodule -Isrc/input -Inetcdf/includes -Isrc/data -Isrc/inc -Isrc/atmosphere -Isrc/util -Isrc/output -Isrc/ecodomain -Isrc/vegetation -Isrc/snowsoil -Isrc/disturb -Isrc/lookup -Isrc/ecodomain/layer -I$(QTDIR)/include
LINK     = g++
LFLAGS   = 
LIBS     = $(SUBLIBS) -L$(QTDIR)/lib -lqt-mt -lXext -lX11 -lm -Lnetcdf/libs -lnetcdf_c++ -lnetcdf
AR       = ar cqs
RANLIB   = 
MOC      = $(QTDIR)/bin/moc
UIC      = $(QTDIR)/bin/uic
QMAKE    = qmake
TAR      = tar -cf
GZIP     = gzip -9f
COPY     = cp -f
COPY_FILE= $(COPY)
COPY_DIR = $(COPY) -r
INSTALL_FILE= $(COPY_FILE)
INSTALL_DIR = $(COPY_DIR)
DEL_FILE = rm -f
SYMLINK  = ln -sf
DEL_DIR  = rmdir
MOVE     = mv -f
CHK_DIR_EXISTS= test -d
MKDIR    = mkdir -p

####### Output directory

OBJECTS_DIR = ./

####### Files

HEADERS = netcdf/includes/ncvalues.h \
		netcdf/includes/netcdf.h \
		netcdf/includes/netcdf.hh \
		netcdf/includes/netcdfcpp.h \
		src/assembler/RunCohort.h \
		src/assembler/RunGrid.h \
		src/assembler/Runner.h \
		src/assembler/RunRegion.h \
		src/atmosphere/Atmosphere.h \
		src/atmosphere/AtmosUtil.h \
		src/data/BgcData.h \
		src/data/CohortData.h \
		src/data/EnvData.h \
		src/data/EnvDataDly.h \
		src/data/FirData.h \
		src/data/GridData.h \
		src/data/OutDataRegn.h \
		src/data/RegionData.h \
		src/data/RestartData.h \
		src/disturb/WildFire.h \
		src/ecodomain/DoubleLinkedList.h \
		src/ecodomain/Ground.h \
		src/ecodomain/Mineral.h \
		src/ecodomain/Moss.h \
		src/ecodomain/Organic.h \
		src/ecodomain/Snow.h \
		src/ecodomain/SoilParent.h \
		src/ecodomain/Vegetation.h \
		src/inc/cohortconst.h \
		src/inc/diagnostics.h \
		src/inc/ErrorCode.h \
		src/inc/fluxes.h \
		src/inc/layerconst.h \
		src/inc/parameters.h \
		src/inc/physicalconst.h \
		src/inc/states.h \
		src/inc/temconst.h \
		src/inc/timeconst.h \
		src/input/CohortInputer.h \
		src/input/GridInputer.h \
		src/input/RegionInputer.h \
		src/input/RestartInputer.h \
		src/lookup/CohortLookup.h \
		src/lookup/SoilLookup.h \
		src/output/BgcOutputer.h \
		src/output/ChtOutputer.h \
		src/output/EnvOutputer.h \
		src/output/RegnOutputer.h \
		src/output/RestartOutputer.h \
		src/output/StatusOutputer.h \
		src/runmodule/Cohort.h \
		src/runmodule/Controller.h \
		src/runmodule/Grid.h \
		src/runmodule/Integrator.h \
		src/runmodule/ModelData.h \
		src/runmodule/OutRetrive.h \
		src/runmodule/Region.h \
		src/runmodule/Timer.h \
		src/snowsoil/Richards.h \
		src/snowsoil/Snow_Env.h \
		src/snowsoil/Soil_Bgc.h \
		src/snowsoil/Soil_Env.h \
		src/snowsoil/SoilParent_Env.h \
		src/snowsoil/Stefan.h \
		src/util/CrankNicholson.h \
		src/util/Interpolator.h \
		src/vegetation/Vegetation_Bgc.h \
		src/vegetation/Vegetation_Env.h \
		src/ecodomain/layer/Layer.h \
		src/ecodomain/layer/MineralLayer.h \
		src/ecodomain/layer/MossLayer.h \
		src/ecodomain/layer/OrganicLayer.h \
		src/ecodomain/layer/ParentLayer.h \
		src/ecodomain/layer/SnowLayer.h \
		src/ecodomain/layer/SoilLayer.h
SOURCES = src/TEM.cpp \
		src/assembler/RunCohort.cpp \
		src/assembler/RunGrid.cpp \
		src/assembler/Runner.cpp \
		src/assembler/RunRegion.cpp \
		src/atmosphere/Atmosphere.cpp \
		src/atmosphere/AtmosUtil.cpp \
		src/data/BgcData.cpp \
		src/data/CohortData.cpp \
		src/data/EnvData.cpp \
		src/data/EnvDataDly.cpp \
		src/data/FirData.cpp \
		src/data/GridData.cpp \
		src/data/OutDataRegn.cpp \
		src/data/RegionData.cpp \
		src/data/RestartData.cpp \
		src/disturb/WildFire.cpp \
		src/ecodomain/DoubleLinkedList.cpp \
		src/ecodomain/Ground.cpp \
		src/ecodomain/Mineral.cpp \
		src/ecodomain/Moss.cpp \
		src/ecodomain/Organic.cpp \
		src/ecodomain/Snow.cpp \
		src/ecodomain/SoilParent.cpp \
		src/ecodomain/Vegetation.cpp \
		src/input/CohortInputer.cpp \
		src/input/GridInputer.cpp \
		src/input/RegionInputer.cpp \
		src/input/RestartInputer.cpp \
		src/lookup/CohortLookup.cpp \
		src/lookup/SoilLookup.cpp \
		src/output/BgcOutputer.cpp \
		src/output/ChtOutputer.cpp \
		src/output/EnvOutputer.cpp \
		src/output/RegnOutputer.cpp \
		src/output/RestartOutputer.cpp \
		src/output/StatusOutputer.cpp \
		src/runmodule/Cohort.cpp \
		src/runmodule/Controller.cpp \
		src/runmodule/Grid.cpp \
		src/runmodule/Integrator.cpp \
		src/runmodule/ModelData.cpp \
		src/runmodule/OutRetrive.cpp \
		src/runmodule/Region.cpp \
		src/runmodule/Timer.cpp \
		src/snowsoil/Richards.cpp \
		src/snowsoil/Snow_Env.cpp \
		src/snowsoil/Soil_Bgc.cpp \
		src/snowsoil/Soil_Env.cpp \
		src/snowsoil/SoilParent_Env.cpp \
		src/snowsoil/Stefan.cpp \
		src/util/CrankNicholson.cpp \
		src/util/Interpolator.cpp \
		src/vegetation/Vegetation_Bgc.cpp \
		src/vegetation/Vegetation_Env.cpp \
		src/ecodomain/layer/Layer.cpp \
		src/ecodomain/layer/MineralLayer.cpp \
		src/ecodomain/layer/MossLayer.cpp \
		src/ecodomain/layer/OrganicLayer.cpp \
		src/ecodomain/layer/ParentLayer.cpp \
		src/ecodomain/layer/SnowLayer.cpp \
		src/ecodomain/layer/SoilLayer.cpp
OBJECTS = TEM.o \
		RunCohort.o \
		RunGrid.o \
		Runner.o \
		RunRegion.o \
		Atmosphere.o \
		AtmosUtil.o \
		BgcData.o \
		CohortData.o \
		EnvData.o \
		EnvDataDly.o \
		FirData.o \
		GridData.o \
		OutDataRegn.o \
		RegionData.o \
		RestartData.o \
		WildFire.o \
		DoubleLinkedList.o \
		Ground.o \
		Mineral.o \
		Moss.o \
		Organic.o \
		Snow.o \
		SoilParent.o \
		Vegetation.o \
		CohortInputer.o \
		GridInputer.o \
		RegionInputer.o \
		RestartInputer.o \
		CohortLookup.o \
		SoilLookup.o \
		BgcOutputer.o \
		ChtOutputer.o \
		EnvOutputer.o \
		RegnOutputer.o \
		RestartOutputer.o \
		StatusOutputer.o \
		Cohort.o \
		Controller.o \
		Grid.o \
		Integrator.o \
		ModelData.o \
		OutRetrive.o \
		Region.o \
		Timer.o \
		Richards.o \
		Snow_Env.o \
		Soil_Bgc.o \
		Soil_Env.o \
		SoilParent_Env.o \
		Stefan.o \
		CrankNicholson.o \
		Interpolator.o \
		Vegetation_Bgc.o \
		Vegetation_Env.o \
		Layer.o \
		MineralLayer.o \
		MossLayer.o \
		OrganicLayer.o \
		ParentLayer.o \
		SnowLayer.o \
		SoilLayer.o
FORMS = 
UICDECLS = 
UICIMPLS = 
SRCMOC   = 
OBJMOC = 
DIST	   = model.pro
QMAKE_TARGET = model
DESTDIR  = 
TARGET   = DVMDOSTEM

first: all
####### Implicit rules

.SUFFIXES: .c .o .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o $@ $<

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(UICDECLS) $(OBJECTS) $(OBJMOC)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJMOC) $(OBJCOMP) $(LIBS)

mocables: $(SRCMOC)
uicables: $(UICDECLS) $(UICIMPLS)

$(MOC): 
	( cd $(QTDIR)/src/moc && $(MAKE) )

Makefile: model.pro  /usr/lib64/qt-3.3/mkspecs/default/qmake.conf /usr/lib64/qt-3.3/lib/libqt-mt.prl
	$(QMAKE) -o Makefile model.pro
qmake: 
	@$(QMAKE) -o Makefile model.pro

dist: 
	@mkdir -p .tmp/model && $(COPY_FILE) --parents $(SOURCES) $(HEADERS) $(FORMS) $(DIST) .tmp/model/ && ( cd `dirname .tmp/model` && $(TAR) model.tar model && $(GZIP) model.tar ) && $(MOVE) `dirname .tmp/model`/model.tar.gz . && $(DEL_FILE) -r .tmp/model

mocclean:

uiclean:

yaccclean:
lexclean:
clean:
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) $(TARGET)


FORCE:

####### Compile

TEM.o: src/TEM.cpp src/assembler/Runner.h \
		src/assembler/RunRegion.h \
		src/assembler/RunGrid.h \
		src/assembler/RunCohort.h \
		src/runmodule/Controller.h \
		src/runmodule/ModelData.h \
		src/input/RegionInputer.h \
		src/runmodule/Region.h \
		netcdf/includes/netcdfcpp.h \
		src/data/RegionData.h \
		netcdf/includes/ncvalues.h \
		netcdf/includes/netcdf.h \
		src/inc/timeconst.h \
		src/inc/ErrorCode.h \
		src/input/GridInputer.h \
		src/runmodule/Grid.h \
		src/inc/layerconst.h \
		src/data/GridData.h \
		src/inc/cohortconst.h \
		src/atmosphere/Atmosphere.h \
		src/data/EnvData.h \
		src/data/BgcData.h \
		src/atmosphere/AtmosUtil.h \
		src/util/Interpolator.h \
		src/inc/diagnostics.h \
		src/inc/fluxes.h \
		src/inc/states.h \
		src/inc/physicalconst.h \
		src/data/CohortData.h \
		src/input/CohortInputer.h \
		src/input/RestartInputer.h \
		src/output/StatusOutputer.h \
		src/output/ChtOutputer.h \
		src/output/EnvOutputer.h \
		src/output/BgcOutputer.h \
		src/output/RestartOutputer.h \
		src/output/RegnOutputer.h \
		src/runmodule/Cohort.h \
		src/data/RestartData.h \
		src/data/EnvDataDly.h \
		src/data/OutDataRegn.h \
		src/ecodomain/Ground.h \
		src/ecodomain/Vegetation.h \
		src/vegetation/Vegetation_Env.h \
		src/vegetation/Vegetation_Bgc.h \
		src/snowsoil/Snow_Env.h \
		src/snowsoil/Soil_Env.h \
		src/snowsoil/SoilParent_Env.h \
		src/snowsoil/Soil_Bgc.h \
		src/disturb/WildFire.h \
		src/data/FirData.h \
		src/lookup/CohortLookup.h \
		src/runmodule/Integrator.h \
		src/runmodule/Timer.h \
		src/runmodule/OutRetrive.h \
		src/ecodomain/DoubleLinkedList.h \
		src/ecodomain/Snow.h \
		src/ecodomain/Moss.h \
		src/ecodomain/Organic.h \
		src/ecodomain/Mineral.h \
		src/ecodomain/SoilParent.h \
		src/ecodomain/layer/Layer.h \
		src/ecodomain/layer/MossLayer.h \
		src/ecodomain/layer/SnowLayer.h \
		src/ecodomain/layer/MineralLayer.h \
		src/ecodomain/layer/OrganicLayer.h \
		src/ecodomain/layer/ParentLayer.h \
		src/lookup/SoilLookup.h \
		src/inc/parameters.h \
		src/ecodomain/layer/SoilLayer.h \
		src/snowsoil/Stefan.h \
		src/snowsoil/Richards.h \
		src/util/CrankNicholson.h \
		src/inc/temconst.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TEM.o src/TEM.cpp

RunCohort.o: src/assembler/RunCohort.cpp src/assembler/RunCohort.h \
		src/input/CohortInputer.h \
		src/input/RestartInputer.h \
		src/output/StatusOutputer.h \
		src/output/ChtOutputer.h \
		src/output/EnvOutputer.h \
		src/output/BgcOutputer.h \
		src/output/RestartOutputer.h \
		src/output/RegnOutputer.h \
		src/runmodule/Cohort.h \
		netcdf/includes/netcdfcpp.h \
		src/runmodule/ModelData.h \
		src/inc/cohortconst.h \
		src/inc/layerconst.h \
		src/inc/timeconst.h \
		src/inc/ErrorCode.h \
		netcdf/includes/ncvalues.h \
		netcdf/includes/netcdf.h \
		src/data/RestartData.h \
		src/data/CohortData.h \
		src/inc/states.h \
		src/inc/diagnostics.h \
		src/data/RegionData.h \
		src/data/GridData.h \
		src/data/EnvData.h \
		src/data/EnvDataDly.h \
		src/inc/fluxes.h \
		src/inc/physicalconst.h \
		src/data/BgcData.h \
		src/data/OutDataRegn.h \
		src/ecodomain/Ground.h \
		src/ecodomain/Vegetation.h \
		src/atmosphere/Atmosphere.h \
		src/vegetation/Vegetation_Env.h \
		src/vegetation/Vegetation_Bgc.h \
		src/snowsoil/Snow_Env.h \
		src/snowsoil/Soil_Env.h \
		src/snowsoil/SoilParent_Env.h \
		src/snowsoil/Soil_Bgc.h \
		src/disturb/WildFire.h \
		src/data/FirData.h \
		src/lookup/CohortLookup.h \
		src/runmodule/Integrator.h \
		src/runmodule/Timer.h \
		src/runmodule/OutRetrive.h \
		src/ecodomain/DoubleLinkedList.h \
		src/ecodomain/Snow.h \
		src/ecodomain/Moss.h \
		src/ecodomain/Organic.h \
		src/ecodomain/Mineral.h \
		src/ecodomain/SoilParent.h \
		src/ecodomain/layer/Layer.h \
		src/ecodomain/layer/MossLayer.h \
		src/ecodomain/layer/SnowLayer.h \
		src/ecodomain/layer/MineralLayer.h \
		src/ecodomain/layer/OrganicLayer.h \
		src/ecodomain/layer/ParentLayer.h \
		src/lookup/SoilLookup.h \
		src/inc/parameters.h \
		src/ecodomain/layer/SoilLayer.h \
		src/atmosphere/AtmosUtil.h \
		src/util/Interpolator.h \
		src/snowsoil/Stefan.h \
		src/snowsoil/Richards.h \
		src/util/CrankNicholson.h \
		src/inc/temconst.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o RunCohort.o src/assembler/RunCohort.cpp

RunGrid.o: src/assembler/RunGrid.cpp src/assembler/RunGrid.h \
		src/input/GridInputer.h \
		src/runmodule/Grid.h \
		netcdf/includes/netcdfcpp.h \
		src/inc/layerconst.h \
		src/inc/ErrorCode.h \
		src/data/GridData.h \
		src/runmodule/ModelData.h \
		netcdf/includes/ncvalues.h \
		netcdf/includes/netcdf.h \
		src/inc/timeconst.h \
		src/inc/cohortconst.h \
		src/atmosphere/Atmosphere.h \
		src/data/RegionData.h \
		src/data/EnvData.h \
		src/data/BgcData.h \
		src/atmosphere/AtmosUtil.h \
		src/util/Interpolator.h \
		src/inc/diagnostics.h \
		src/inc/fluxes.h \
		src/inc/states.h \
		src/inc/physicalconst.h \
		src/data/CohortData.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o RunGrid.o src/assembler/RunGrid.cpp

Runner.o: src/assembler/Runner.cpp src/assembler/Runner.h \
		src/assembler/RunRegion.h \
		src/assembler/RunGrid.h \
		src/assembler/RunCohort.h \
		src/runmodule/Controller.h \
		src/runmodule/ModelData.h \
		src/input/RegionInputer.h \
		src/runmodule/Region.h \
		netcdf/includes/netcdfcpp.h \
		src/data/RegionData.h \
		netcdf/includes/ncvalues.h \
		netcdf/includes/netcdf.h \
		src/inc/timeconst.h \
		src/inc/ErrorCode.h \
		src/input/GridInputer.h \
		src/runmodule/Grid.h \
		src/inc/layerconst.h \
		src/data/GridData.h \
		src/inc/cohortconst.h \
		src/atmosphere/Atmosphere.h \
		src/data/EnvData.h \
		src/data/BgcData.h \
		src/atmosphere/AtmosUtil.h \
		src/util/Interpolator.h \
		src/inc/diagnostics.h \
		src/inc/fluxes.h \
		src/inc/states.h \
		src/inc/physicalconst.h \
		src/data/CohortData.h \
		src/input/CohortInputer.h \
		src/input/RestartInputer.h \
		src/output/StatusOutputer.h \
		src/output/ChtOutputer.h \
		src/output/EnvOutputer.h \
		src/output/BgcOutputer.h \
		src/output/RestartOutputer.h \
		src/output/RegnOutputer.h \
		src/runmodule/Cohort.h \
		src/data/RestartData.h \
		src/data/EnvDataDly.h \
		src/data/OutDataRegn.h \
		src/ecodomain/Ground.h \
		src/ecodomain/Vegetation.h \
		src/vegetation/Vegetation_Env.h \
		src/vegetation/Vegetation_Bgc.h \
		src/snowsoil/Snow_Env.h \
		src/snowsoil/Soil_Env.h \
		src/snowsoil/SoilParent_Env.h \
		src/snowsoil/Soil_Bgc.h \
		src/disturb/WildFire.h \
		src/data/FirData.h \
		src/lookup/CohortLookup.h \
		src/runmodule/Integrator.h \
		src/runmodule/Timer.h \
		src/runmodule/OutRetrive.h \
		src/ecodomain/DoubleLinkedList.h \
		src/ecodomain/Snow.h \
		src/ecodomain/Moss.h \
		src/ecodomain/Organic.h \
		src/ecodomain/Mineral.h \
		src/ecodomain/SoilParent.h \
		src/ecodomain/layer/Layer.h \
		src/ecodomain/layer/MossLayer.h \
		src/ecodomain/layer/SnowLayer.h \
		src/ecodomain/layer/MineralLayer.h \
		src/ecodomain/layer/OrganicLayer.h \
		src/ecodomain/layer/ParentLayer.h \
		src/lookup/SoilLookup.h \
		src/inc/parameters.h \
		src/ecodomain/layer/SoilLayer.h \
		src/snowsoil/Stefan.h \
		src/snowsoil/Richards.h \
		src/util/CrankNicholson.h \
		src/inc/temconst.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Runner.o src/assembler/Runner.cpp

RunRegion.o: src/assembler/RunRegion.cpp src/assembler/RunRegion.h \
		src/input/RegionInputer.h \
		src/runmodule/Region.h \
		netcdf/includes/netcdfcpp.h \
		src/data/RegionData.h \
		src/runmodule/ModelData.h \
		netcdf/includes/ncvalues.h \
		netcdf/includes/netcdf.h \
		src/inc/timeconst.h \
		src/inc/ErrorCode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o RunRegion.o src/assembler/RunRegion.cpp

Atmosphere.o: src/atmosphere/Atmosphere.cpp src/atmosphere/Atmosphere.h \
		src/inc/timeconst.h \
		src/atmosphere/AtmosUtil.h \
		src/data/EnvData.h \
		src/data/GridData.h \
		src/data/RegionData.h \
		src/util/Interpolator.h \
		src/inc/diagnostics.h \
		src/inc/fluxes.h \
		src/inc/states.h \
		src/inc/ErrorCode.h \
		src/inc/layerconst.h \
		src/inc/physicalconst.h \
		src/inc/cohortconst.h \
		src/data/CohortData.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Atmosphere.o src/atmosphere/Atmosphere.cpp

AtmosUtil.o: src/atmosphere/AtmosUtil.cpp src/atmosphere/AtmosUtil.h \
		src/util/Interpolator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AtmosUtil.o src/atmosphere/AtmosUtil.cpp

BgcData.o: src/data/BgcData.cpp src/data/BgcData.h \
		src/inc/ErrorCode.h \
		src/inc/diagnostics.h \
		src/inc/fluxes.h \
		src/inc/states.h \
		src/data/EnvData.h \
		src/data/RegionData.h \
		src/data/GridData.h \
		src/data/CohortData.h \
		src/inc/cohortconst.h \
		src/inc/layerconst.h \
		src/inc/timeconst.h \
		src/inc/physicalconst.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BgcData.o src/data/BgcData.cpp

CohortData.o: src/data/CohortData.cpp src/data/CohortData.h \
		src/inc/ErrorCode.h \
		src/inc/timeconst.h \
		src/inc/cohortconst.h \
		src/inc/states.h \
		src/inc/diagnostics.h \
		src/data/RegionData.h \
		src/data/GridData.h \
		src/inc/layerconst.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CohortData.o src/data/CohortData.cpp

EnvData.o: src/data/EnvData.cpp src/data/EnvData.h \
		src/inc/diagnostics.h \
		src/inc/fluxes.h \
		src/inc/states.h \
		src/inc/ErrorCode.h \
		src/inc/layerconst.h \
		src/inc/timeconst.h \
		src/inc/physicalconst.h \
		src/inc/cohortconst.h \
		src/data/RegionData.h \
		src/data/GridData.h \
		src/data/CohortData.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o EnvData.o src/data/EnvData.cpp

EnvDataDly.o: src/data/EnvDataDly.cpp src/data/EnvDataDly.h \
		src/inc/diagnostics.h \
		src/inc/fluxes.h \
		src/inc/states.h \
		src/inc/ErrorCode.h \
		src/inc/layerconst.h \
		src/inc/timeconst.h \
		src/inc/physicalconst.h \
		src/inc/cohortconst.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o EnvDataDly.o src/data/EnvDataDly.cpp

FirData.o: src/data/FirData.cpp src/data/FirData.h \
		src/inc/diagnostics.h \
		src/inc/fluxes.h \
		src/inc/states.h \
		src/inc/timeconst.h \
		src/inc/cohortconst.h \
		src/inc/layerconst.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FirData.o src/data/FirData.cpp

GridData.o: src/data/GridData.cpp src/data/GridData.h \
		src/inc/timeconst.h \
		src/inc/cohortconst.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GridData.o src/data/GridData.cpp

OutDataRegn.o: src/data/OutDataRegn.cpp src/data/OutDataRegn.h \
		src/inc/ErrorCode.h \
		src/inc/timeconst.h \
		src/inc/cohortconst.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o OutDataRegn.o src/data/OutDataRegn.cpp

RegionData.o: src/data/RegionData.cpp src/data/RegionData.h \
		src/inc/timeconst.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o RegionData.o src/data/RegionData.cpp

RestartData.o: src/data/RestartData.cpp src/data/RestartData.h \
		src/inc/ErrorCode.h \
		src/inc/cohortconst.h \
		src/inc/layerconst.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o RestartData.o src/data/RestartData.cpp

WildFire.o: src/disturb/WildFire.cpp src/disturb/WildFire.h \
		src/data/CohortData.h \
		src/data/EnvData.h \
		src/data/FirData.h \
		src/data/BgcData.h \
		src/data/RestartData.h \
		src/inc/ErrorCode.h \
		src/inc/timeconst.h \
		src/inc/parameters.h \
		src/lookup/CohortLookup.h \
		src/inc/cohortconst.h \
		src/inc/states.h \
		src/inc/diagnostics.h \
		src/data/RegionData.h \
		src/data/GridData.h \
		src/inc/layerconst.h \
		src/inc/fluxes.h \
		src/inc/physicalconst.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o WildFire.o src/disturb/WildFire.cpp

DoubleLinkedList.o: src/ecodomain/DoubleLinkedList.cpp src/ecodomain/DoubleLinkedList.h \
		src/ecodomain/layer/Layer.h \
		src/ecodomain/layer/SoilLayer.h \
		src/inc/ErrorCode.h \
		src/inc/physicalconst.h \
		src/inc/layerconst.h \
		src/lookup/SoilLookup.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DoubleLinkedList.o src/ecodomain/DoubleLinkedList.cpp

Ground.o: src/ecodomain/Ground.cpp src/ecodomain/Ground.h \
		src/ecodomain/DoubleLinkedList.h \
		src/ecodomain/Snow.h \
		src/ecodomain/Moss.h \
		src/ecodomain/Organic.h \
		src/ecodomain/Mineral.h \
		src/ecodomain/SoilParent.h \
		src/ecodomain/layer/Layer.h \
		src/ecodomain/layer/MossLayer.h \
		src/ecodomain/layer/SnowLayer.h \
		src/ecodomain/layer/MineralLayer.h \
		src/ecodomain/layer/OrganicLayer.h \
		src/ecodomain/layer/ParentLayer.h \
		src/lookup/SoilLookup.h \
		src/lookup/CohortLookup.h \
		src/data/CohortData.h \
		src/data/FirData.h \
		src/data/RestartData.h \
		src/inc/parameters.h \
		src/ecodomain/layer/SoilLayer.h \
		src/inc/ErrorCode.h \
		src/inc/physicalconst.h \
		src/inc/layerconst.h \
		src/inc/cohortconst.h \
		src/inc/timeconst.h \
		src/inc/states.h \
		src/inc/diagnostics.h \
		src/data/RegionData.h \
		src/data/GridData.h \
		src/inc/fluxes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Ground.o src/ecodomain/Ground.cpp

Mineral.o: src/ecodomain/Mineral.cpp src/ecodomain/Mineral.h \
		src/inc/layerconst.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Mineral.o src/ecodomain/Mineral.cpp

Moss.o: src/ecodomain/Moss.cpp src/ecodomain/Moss.h \
		src/inc/cohortconst.h \
		src/inc/layerconst.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Moss.o src/ecodomain/Moss.cpp

Organic.o: src/ecodomain/Organic.cpp src/ecodomain/Organic.h \
		src/inc/ErrorCode.h \
		src/inc/cohortconst.h \
		src/inc/layerconst.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Organic.o src/ecodomain/Organic.cpp

Snow.o: src/ecodomain/Snow.cpp src/ecodomain/Snow.h \
		src/ecodomain/layer/SnowLayer.h \
		src/inc/ErrorCode.h \
		src/inc/layerconst.h \
		src/ecodomain/layer/Layer.h \
		src/inc/physicalconst.h \
		src/inc/parameters.h \
		src/inc/cohortconst.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Snow.o src/ecodomain/Snow.cpp

SoilParent.o: src/ecodomain/SoilParent.cpp src/ecodomain/SoilParent.h \
		src/ecodomain/layer/ParentLayer.h \
		src/inc/ErrorCode.h \
		src/inc/layerconst.h \
		src/ecodomain/layer/Layer.h \
		src/inc/physicalconst.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SoilParent.o src/ecodomain/SoilParent.cpp

Vegetation.o: src/ecodomain/Vegetation.cpp src/ecodomain/Vegetation.h \
		src/lookup/CohortLookup.h \
		src/data/EnvData.h \
		src/data/BgcData.h \
		src/data/CohortData.h \
		src/data/RestartData.h \
		src/inc/ErrorCode.h \
		src/inc/parameters.h \
		src/inc/cohortconst.h \
		src/inc/timeconst.h \
		src/inc/layerconst.h \
		src/inc/diagnostics.h \
		src/inc/fluxes.h \
		src/inc/states.h \
		src/inc/physicalconst.h \
		src/data/RegionData.h \
		src/data/GridData.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Vegetation.o src/ecodomain/Vegetation.cpp

CohortInputer.o: src/input/CohortInputer.cpp src/input/CohortInputer.h \
		netcdf/includes/netcdfcpp.h \
		src/runmodule/ModelData.h \
		src/inc/cohortconst.h \
		src/inc/layerconst.h \
		src/inc/timeconst.h \
		src/inc/ErrorCode.h \
		netcdf/includes/ncvalues.h \
		netcdf/includes/netcdf.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CohortInputer.o src/input/CohortInputer.cpp

GridInputer.o: src/input/GridInputer.cpp src/input/GridInputer.h \
		netcdf/includes/netcdfcpp.h \
		src/inc/layerconst.h \
		src/inc/ErrorCode.h \
		src/data/GridData.h \
		src/runmodule/ModelData.h \
		netcdf/includes/ncvalues.h \
		netcdf/includes/netcdf.h \
		src/inc/timeconst.h \
		src/inc/cohortconst.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GridInputer.o src/input/GridInputer.cpp

RegionInputer.o: src/input/RegionInputer.cpp src/input/RegionInputer.h \
		netcdf/includes/netcdfcpp.h \
		src/data/RegionData.h \
		src/runmodule/ModelData.h \
		netcdf/includes/ncvalues.h \
		netcdf/includes/netcdf.h \
		src/inc/timeconst.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o RegionInputer.o src/input/RegionInputer.cpp

RestartInputer.o: src/input/RestartInputer.cpp src/input/RestartInputer.h \
		netcdf/includes/netcdfcpp.h \
		src/inc/layerconst.h \
		src/inc/timeconst.h \
		src/data/RestartData.h \
		netcdf/includes/ncvalues.h \
		netcdf/includes/netcdf.h \
		src/inc/ErrorCode.h \
		src/inc/cohortconst.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o RestartInputer.o src/input/RestartInputer.cpp

CohortLookup.o: src/lookup/CohortLookup.cpp src/lookup/CohortLookup.h \
		src/inc/cohortconst.h \
		src/inc/timeconst.h \
		src/inc/layerconst.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CohortLookup.o src/lookup/CohortLookup.cpp

SoilLookup.o: src/lookup/SoilLookup.cpp src/lookup/SoilLookup.h \
		src/inc/physicalconst.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SoilLookup.o src/lookup/SoilLookup.cpp

BgcOutputer.o: src/output/BgcOutputer.cpp src/output/BgcOutputer.h \
		netcdf/includes/netcdfcpp.h \
		src/inc/timeconst.h \
		src/inc/cohortconst.h \
		src/inc/layerconst.h \
		src/inc/ErrorCode.h \
		src/data/BgcData.h \
		netcdf/includes/ncvalues.h \
		netcdf/includes/netcdf.h \
		src/inc/diagnostics.h \
		src/inc/fluxes.h \
		src/inc/states.h \
		src/data/EnvData.h \
		src/data/RegionData.h \
		src/data/GridData.h \
		src/data/CohortData.h \
		src/inc/physicalconst.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BgcOutputer.o src/output/BgcOutputer.cpp

ChtOutputer.o: src/output/ChtOutputer.cpp src/output/ChtOutputer.h \
		netcdf/includes/netcdfcpp.h \
		src/inc/ErrorCode.h \
		src/data/CohortData.h \
		netcdf/includes/ncvalues.h \
		netcdf/includes/netcdf.h \
		src/inc/timeconst.h \
		src/inc/cohortconst.h \
		src/inc/states.h \
		src/inc/diagnostics.h \
		src/data/RegionData.h \
		src/data/GridData.h \
		src/inc/layerconst.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ChtOutputer.o src/output/ChtOutputer.cpp

EnvOutputer.o: src/output/EnvOutputer.cpp src/output/EnvOutputer.h \
		netcdf/includes/netcdfcpp.h \
		src/data/EnvData.h \
		src/data/EnvDataDly.h \
		src/inc/ErrorCode.h \
		src/inc/timeconst.h \
		src/inc/layerconst.h \
		netcdf/includes/ncvalues.h \
		netcdf/includes/netcdf.h \
		src/inc/diagnostics.h \
		src/inc/fluxes.h \
		src/inc/states.h \
		src/inc/physicalconst.h \
		src/inc/cohortconst.h \
		src/data/RegionData.h \
		src/data/GridData.h \
		src/data/CohortData.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o EnvOutputer.o src/output/EnvOutputer.cpp

RegnOutputer.o: src/output/RegnOutputer.cpp src/output/RegnOutputer.h \
		netcdf/includes/netcdfcpp.h \
		src/inc/ErrorCode.h \
		src/data/OutDataRegn.h \
		netcdf/includes/ncvalues.h \
		netcdf/includes/netcdf.h \
		src/inc/timeconst.h \
		src/inc/cohortconst.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o RegnOutputer.o src/output/RegnOutputer.cpp

RestartOutputer.o: src/output/RestartOutputer.cpp src/output/RestartOutputer.h \
		netcdf/includes/netcdfcpp.h \
		src/data/RestartData.h \
		netcdf/includes/ncvalues.h \
		netcdf/includes/netcdf.h \
		src/inc/ErrorCode.h \
		src/inc/cohortconst.h \
		src/inc/layerconst.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o RestartOutputer.o src/output/RestartOutputer.cpp

StatusOutputer.o: src/output/StatusOutputer.cpp src/output/StatusOutputer.h \
		netcdf/includes/netcdfcpp.h \
		src/inc/timeconst.h \
		netcdf/includes/ncvalues.h \
		netcdf/includes/netcdf.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o StatusOutputer.o src/output/StatusOutputer.cpp

Cohort.o: src/runmodule/Cohort.cpp src/runmodule/Cohort.h \
		src/ecodomain/Ground.h \
		src/ecodomain/Vegetation.h \
		src/atmosphere/Atmosphere.h \
		src/vegetation/Vegetation_Env.h \
		src/vegetation/Vegetation_Bgc.h \
		src/snowsoil/Snow_Env.h \
		src/snowsoil/Soil_Env.h \
		src/snowsoil/SoilParent_Env.h \
		src/snowsoil/Soil_Bgc.h \
		src/disturb/WildFire.h \
		src/data/RegionData.h \
		src/data/GridData.h \
		src/data/CohortData.h \
		src/data/EnvData.h \
		src/data/BgcData.h \
		src/data/FirData.h \
		src/data/RestartData.h \
		src/lookup/CohortLookup.h \
		src/runmodule/Integrator.h \
		src/runmodule/Timer.h \
		src/runmodule/ModelData.h \
		src/runmodule/OutRetrive.h \
		src/ecodomain/DoubleLinkedList.h \
		src/ecodomain/Snow.h \
		src/ecodomain/Moss.h \
		src/ecodomain/Organic.h \
		src/ecodomain/Mineral.h \
		src/ecodomain/SoilParent.h \
		src/ecodomain/layer/Layer.h \
		src/ecodomain/layer/MossLayer.h \
		src/ecodomain/layer/SnowLayer.h \
		src/ecodomain/layer/MineralLayer.h \
		src/ecodomain/layer/OrganicLayer.h \
		src/ecodomain/layer/ParentLayer.h \
		src/lookup/SoilLookup.h \
		src/inc/parameters.h \
		src/ecodomain/layer/SoilLayer.h \
		src/inc/ErrorCode.h \
		src/inc/physicalconst.h \
		src/inc/layerconst.h \
		src/inc/cohortconst.h \
		src/inc/timeconst.h \
		src/inc/states.h \
		src/inc/diagnostics.h \
		src/inc/fluxes.h \
		src/atmosphere/AtmosUtil.h \
		src/util/Interpolator.h \
		src/snowsoil/Stefan.h \
		src/snowsoil/Richards.h \
		src/util/CrankNicholson.h \
		src/inc/temconst.h \
		src/data/OutDataRegn.h \
		src/data/EnvDataDly.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Cohort.o src/runmodule/Cohort.cpp

Controller.o: src/runmodule/Controller.cpp src/runmodule/Controller.h \
		src/runmodule/ModelData.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Controller.o src/runmodule/Controller.cpp

Grid.o: src/runmodule/Grid.cpp src/runmodule/Grid.h \
		src/atmosphere/Atmosphere.h \
		src/data/GridData.h \
		src/data/RegionData.h \
		src/data/EnvData.h \
		src/data/BgcData.h \
		src/inc/ErrorCode.h \
		src/inc/timeconst.h \
		src/atmosphere/AtmosUtil.h \
		src/util/Interpolator.h \
		src/inc/diagnostics.h \
		src/inc/fluxes.h \
		src/inc/states.h \
		src/inc/layerconst.h \
		src/inc/physicalconst.h \
		src/inc/cohortconst.h \
		src/data/CohortData.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Grid.o src/runmodule/Grid.cpp

Integrator.o: src/runmodule/Integrator.cpp src/runmodule/Integrator.h \
		src/snowsoil/Soil_Bgc.h \
		src/vegetation/Vegetation_Bgc.h \
		src/inc/temconst.h \
		src/inc/ErrorCode.h \
		src/data/CohortData.h \
		src/data/EnvData.h \
		src/data/FirData.h \
		src/data/BgcData.h \
		src/data/RestartData.h \
		src/lookup/CohortLookup.h \
		src/runmodule/ModelData.h \
		src/inc/parameters.h \
		src/ecodomain/Ground.h \
		src/inc/timeconst.h \
		src/inc/cohortconst.h \
		src/inc/states.h \
		src/inc/diagnostics.h \
		src/data/RegionData.h \
		src/data/GridData.h \
		src/inc/layerconst.h \
		src/inc/fluxes.h \
		src/inc/physicalconst.h \
		src/ecodomain/DoubleLinkedList.h \
		src/ecodomain/Snow.h \
		src/ecodomain/Moss.h \
		src/ecodomain/Organic.h \
		src/ecodomain/Mineral.h \
		src/ecodomain/SoilParent.h \
		src/ecodomain/layer/Layer.h \
		src/ecodomain/layer/MossLayer.h \
		src/ecodomain/layer/SnowLayer.h \
		src/ecodomain/layer/MineralLayer.h \
		src/ecodomain/layer/OrganicLayer.h \
		src/ecodomain/layer/ParentLayer.h \
		src/lookup/SoilLookup.h \
		src/ecodomain/layer/SoilLayer.h \
		src/ecodomain/Vegetation.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Integrator.o src/runmodule/Integrator.cpp

ModelData.o: src/runmodule/ModelData.cpp src/runmodule/ModelData.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ModelData.o src/runmodule/ModelData.cpp

OutRetrive.o: src/runmodule/OutRetrive.cpp src/runmodule/OutRetrive.h \
		src/runmodule/Timer.h \
		src/runmodule/ModelData.h \
		src/data/EnvData.h \
		src/data/BgcData.h \
		src/data/FirData.h \
		src/data/RestartData.h \
		src/data/OutDataRegn.h \
		src/data/EnvDataDly.h \
		src/inc/timeconst.h \
		src/inc/cohortconst.h \
		src/inc/ErrorCode.h \
		src/inc/diagnostics.h \
		src/inc/fluxes.h \
		src/inc/states.h \
		src/inc/layerconst.h \
		src/inc/physicalconst.h \
		src/data/RegionData.h \
		src/data/GridData.h \
		src/data/CohortData.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o OutRetrive.o src/runmodule/OutRetrive.cpp

Region.o: src/runmodule/Region.cpp src/runmodule/Region.h \
		src/data/RegionData.h \
		src/inc/ErrorCode.h \
		src/inc/timeconst.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Region.o src/runmodule/Region.cpp

Timer.o: src/runmodule/Timer.cpp src/runmodule/Timer.h \
		src/runmodule/ModelData.h \
		src/inc/timeconst.h \
		src/inc/cohortconst.h \
		src/inc/ErrorCode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Timer.o src/runmodule/Timer.cpp

Richards.o: src/snowsoil/Richards.cpp src/snowsoil/Richards.h \
		src/data/CohortData.h \
		src/data/EnvData.h \
		src/ecodomain/layer/Layer.h \
		src/ecodomain/layer/SoilLayer.h \
		src/util/CrankNicholson.h \
		src/inc/ErrorCode.h \
		src/inc/timeconst.h \
		src/inc/cohortconst.h \
		src/inc/states.h \
		src/inc/diagnostics.h \
		src/data/RegionData.h \
		src/data/GridData.h \
		src/inc/layerconst.h \
		src/inc/fluxes.h \
		src/inc/physicalconst.h \
		src/lookup/SoilLookup.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Richards.o src/snowsoil/Richards.cpp

Snow_Env.o: src/snowsoil/Snow_Env.cpp src/snowsoil/Snow_Env.h \
		src/inc/ErrorCode.h \
		src/data/CohortData.h \
		src/data/EnvData.h \
		src/data/RestartData.h \
		src/ecodomain/Ground.h \
		src/lookup/CohortLookup.h \
		src/inc/timeconst.h \
		src/inc/cohortconst.h \
		src/inc/states.h \
		src/inc/diagnostics.h \
		src/data/RegionData.h \
		src/data/GridData.h \
		src/inc/layerconst.h \
		src/inc/fluxes.h \
		src/inc/physicalconst.h \
		src/ecodomain/DoubleLinkedList.h \
		src/ecodomain/Snow.h \
		src/ecodomain/Moss.h \
		src/ecodomain/Organic.h \
		src/ecodomain/Mineral.h \
		src/ecodomain/SoilParent.h \
		src/ecodomain/layer/Layer.h \
		src/ecodomain/layer/MossLayer.h \
		src/ecodomain/layer/SnowLayer.h \
		src/ecodomain/layer/MineralLayer.h \
		src/ecodomain/layer/OrganicLayer.h \
		src/ecodomain/layer/ParentLayer.h \
		src/lookup/SoilLookup.h \
		src/data/FirData.h \
		src/inc/parameters.h \
		src/ecodomain/layer/SoilLayer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Snow_Env.o src/snowsoil/Snow_Env.cpp

Soil_Bgc.o: src/snowsoil/Soil_Bgc.cpp src/snowsoil/Soil_Bgc.h \
		src/inc/ErrorCode.h \
		src/data/CohortData.h \
		src/data/EnvData.h \
		src/data/FirData.h \
		src/data/BgcData.h \
		src/data/RestartData.h \
		src/lookup/CohortLookup.h \
		src/runmodule/ModelData.h \
		src/inc/parameters.h \
		src/ecodomain/Ground.h \
		src/inc/timeconst.h \
		src/inc/cohortconst.h \
		src/inc/states.h \
		src/inc/diagnostics.h \
		src/data/RegionData.h \
		src/data/GridData.h \
		src/inc/layerconst.h \
		src/inc/fluxes.h \
		src/inc/physicalconst.h \
		src/ecodomain/DoubleLinkedList.h \
		src/ecodomain/Snow.h \
		src/ecodomain/Moss.h \
		src/ecodomain/Organic.h \
		src/ecodomain/Mineral.h \
		src/ecodomain/SoilParent.h \
		src/ecodomain/layer/Layer.h \
		src/ecodomain/layer/MossLayer.h \
		src/ecodomain/layer/SnowLayer.h \
		src/ecodomain/layer/MineralLayer.h \
		src/ecodomain/layer/OrganicLayer.h \
		src/ecodomain/layer/ParentLayer.h \
		src/lookup/SoilLookup.h \
		src/ecodomain/layer/SoilLayer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Soil_Bgc.o src/snowsoil/Soil_Bgc.cpp

Soil_Env.o: src/snowsoil/Soil_Env.cpp src/snowsoil/Soil_Env.h \
		src/snowsoil/Stefan.h \
		src/snowsoil/Richards.h \
		src/data/CohortData.h \
		src/data/EnvData.h \
		src/data/FirData.h \
		src/data/RestartData.h \
		src/inc/ErrorCode.h \
		src/inc/parameters.h \
		src/inc/layerconst.h \
		src/lookup/CohortLookup.h \
		src/ecodomain/Ground.h \
		src/util/CrankNicholson.h \
		src/ecodomain/DoubleLinkedList.h \
		src/ecodomain/Snow.h \
		src/ecodomain/Moss.h \
		src/ecodomain/Organic.h \
		src/ecodomain/Mineral.h \
		src/ecodomain/SoilParent.h \
		src/ecodomain/layer/Layer.h \
		src/ecodomain/layer/MossLayer.h \
		src/ecodomain/layer/SnowLayer.h \
		src/ecodomain/layer/MineralLayer.h \
		src/ecodomain/layer/OrganicLayer.h \
		src/ecodomain/layer/ParentLayer.h \
		src/lookup/SoilLookup.h \
		src/ecodomain/layer/SoilLayer.h \
		src/inc/physicalconst.h \
		src/inc/cohortconst.h \
		src/inc/timeconst.h \
		src/inc/states.h \
		src/inc/diagnostics.h \
		src/data/RegionData.h \
		src/data/GridData.h \
		src/inc/fluxes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Soil_Env.o src/snowsoil/Soil_Env.cpp

SoilParent_Env.o: src/snowsoil/SoilParent_Env.cpp src/snowsoil/SoilParent_Env.h \
		src/data/EnvData.h \
		src/data/RestartData.h \
		src/ecodomain/Ground.h \
		src/inc/diagnostics.h \
		src/inc/fluxes.h \
		src/inc/states.h \
		src/inc/ErrorCode.h \
		src/inc/layerconst.h \
		src/inc/timeconst.h \
		src/inc/physicalconst.h \
		src/inc/cohortconst.h \
		src/data/RegionData.h \
		src/data/GridData.h \
		src/data/CohortData.h \
		src/ecodomain/DoubleLinkedList.h \
		src/ecodomain/Snow.h \
		src/ecodomain/Moss.h \
		src/ecodomain/Organic.h \
		src/ecodomain/Mineral.h \
		src/ecodomain/SoilParent.h \
		src/ecodomain/layer/Layer.h \
		src/ecodomain/layer/MossLayer.h \
		src/ecodomain/layer/SnowLayer.h \
		src/ecodomain/layer/MineralLayer.h \
		src/ecodomain/layer/OrganicLayer.h \
		src/ecodomain/layer/ParentLayer.h \
		src/lookup/SoilLookup.h \
		src/lookup/CohortLookup.h \
		src/data/FirData.h \
		src/inc/parameters.h \
		src/ecodomain/layer/SoilLayer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SoilParent_Env.o src/snowsoil/SoilParent_Env.cpp

Stefan.o: src/snowsoil/Stefan.cpp src/snowsoil/Stefan.h \
		src/ecodomain/Ground.h \
		src/inc/ErrorCode.h \
		src/inc/layerconst.h \
		src/util/CrankNicholson.h \
		src/ecodomain/DoubleLinkedList.h \
		src/ecodomain/Snow.h \
		src/ecodomain/Moss.h \
		src/ecodomain/Organic.h \
		src/ecodomain/Mineral.h \
		src/ecodomain/SoilParent.h \
		src/ecodomain/layer/Layer.h \
		src/ecodomain/layer/MossLayer.h \
		src/ecodomain/layer/SnowLayer.h \
		src/ecodomain/layer/MineralLayer.h \
		src/ecodomain/layer/OrganicLayer.h \
		src/ecodomain/layer/ParentLayer.h \
		src/lookup/SoilLookup.h \
		src/lookup/CohortLookup.h \
		src/data/CohortData.h \
		src/data/FirData.h \
		src/data/RestartData.h \
		src/inc/parameters.h \
		src/ecodomain/layer/SoilLayer.h \
		src/inc/physicalconst.h \
		src/inc/cohortconst.h \
		src/inc/timeconst.h \
		src/inc/states.h \
		src/inc/diagnostics.h \
		src/data/RegionData.h \
		src/data/GridData.h \
		src/inc/fluxes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Stefan.o src/snowsoil/Stefan.cpp

CrankNicholson.o: src/util/CrankNicholson.cpp src/util/CrankNicholson.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CrankNicholson.o src/util/CrankNicholson.cpp

Interpolator.o: src/util/Interpolator.cpp src/util/Interpolator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Interpolator.o src/util/Interpolator.cpp

Vegetation_Bgc.o: src/vegetation/Vegetation_Bgc.cpp src/vegetation/Vegetation_Bgc.h \
		src/lookup/CohortLookup.h \
		src/runmodule/ModelData.h \
		src/data/CohortData.h \
		src/data/EnvData.h \
		src/data/FirData.h \
		src/data/BgcData.h \
		src/data/RestartData.h \
		src/inc/parameters.h \
		src/snowsoil/Soil_Bgc.h \
		src/ecodomain/Vegetation.h \
		src/inc/cohortconst.h \
		src/inc/timeconst.h \
		src/inc/layerconst.h \
		src/inc/ErrorCode.h \
		src/inc/states.h \
		src/inc/diagnostics.h \
		src/data/RegionData.h \
		src/data/GridData.h \
		src/inc/fluxes.h \
		src/inc/physicalconst.h \
		src/ecodomain/Ground.h \
		src/ecodomain/DoubleLinkedList.h \
		src/ecodomain/Snow.h \
		src/ecodomain/Moss.h \
		src/ecodomain/Organic.h \
		src/ecodomain/Mineral.h \
		src/ecodomain/SoilParent.h \
		src/ecodomain/layer/Layer.h \
		src/ecodomain/layer/MossLayer.h \
		src/ecodomain/layer/SnowLayer.h \
		src/ecodomain/layer/MineralLayer.h \
		src/ecodomain/layer/OrganicLayer.h \
		src/ecodomain/layer/ParentLayer.h \
		src/lookup/SoilLookup.h \
		src/ecodomain/layer/SoilLayer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Vegetation_Bgc.o src/vegetation/Vegetation_Bgc.cpp

Vegetation_Env.o: src/vegetation/Vegetation_Env.cpp src/vegetation/Vegetation_Env.h \
		src/lookup/CohortLookup.h \
		src/inc/states.h \
		src/inc/fluxes.h \
		src/inc/diagnostics.h \
		src/inc/parameters.h \
		src/data/CohortData.h \
		src/data/EnvData.h \
		src/data/FirData.h \
		src/data/RestartData.h \
		src/inc/cohortconst.h \
		src/inc/timeconst.h \
		src/inc/layerconst.h \
		src/inc/ErrorCode.h \
		src/data/RegionData.h \
		src/data/GridData.h \
		src/inc/physicalconst.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Vegetation_Env.o src/vegetation/Vegetation_Env.cpp

Layer.o: src/ecodomain/layer/Layer.cpp src/ecodomain/layer/Layer.h \
		src/inc/ErrorCode.h \
		src/inc/physicalconst.h \
		src/inc/layerconst.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Layer.o src/ecodomain/layer/Layer.cpp

MineralLayer.o: src/ecodomain/layer/MineralLayer.cpp src/ecodomain/layer/MineralLayer.h \
		src/ecodomain/layer/SoilLayer.h \
		src/ecodomain/layer/Layer.h \
		src/lookup/SoilLookup.h \
		src/inc/ErrorCode.h \
		src/inc/physicalconst.h \
		src/inc/layerconst.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MineralLayer.o src/ecodomain/layer/MineralLayer.cpp

MossLayer.o: src/ecodomain/layer/MossLayer.cpp src/ecodomain/layer/MossLayer.h \
		src/ecodomain/layer/SoilLayer.h \
		src/ecodomain/layer/Layer.h \
		src/lookup/SoilLookup.h \
		src/inc/ErrorCode.h \
		src/inc/physicalconst.h \
		src/inc/layerconst.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MossLayer.o src/ecodomain/layer/MossLayer.cpp

OrganicLayer.o: src/ecodomain/layer/OrganicLayer.cpp src/ecodomain/layer/OrganicLayer.h \
		src/ecodomain/layer/SoilLayer.h \
		src/ecodomain/layer/Layer.h \
		src/lookup/SoilLookup.h \
		src/inc/ErrorCode.h \
		src/inc/physicalconst.h \
		src/inc/layerconst.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o OrganicLayer.o src/ecodomain/layer/OrganicLayer.cpp

ParentLayer.o: src/ecodomain/layer/ParentLayer.cpp src/ecodomain/layer/ParentLayer.h \
		src/ecodomain/layer/Layer.h \
		src/inc/ErrorCode.h \
		src/inc/physicalconst.h \
		src/inc/layerconst.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ParentLayer.o src/ecodomain/layer/ParentLayer.cpp

SnowLayer.o: src/ecodomain/layer/SnowLayer.cpp src/ecodomain/layer/SnowLayer.h \
		src/ecodomain/layer/Layer.h \
		src/inc/physicalconst.h \
		src/inc/parameters.h \
		src/inc/ErrorCode.h \
		src/inc/layerconst.h \
		src/inc/cohortconst.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SnowLayer.o src/ecodomain/layer/SnowLayer.cpp

SoilLayer.o: src/ecodomain/layer/SoilLayer.cpp src/ecodomain/layer/SoilLayer.h \
		src/ecodomain/layer/Layer.h \
		src/lookup/SoilLookup.h \
		src/inc/ErrorCode.h \
		src/inc/physicalconst.h \
		src/inc/layerconst.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SoilLayer.o src/ecodomain/layer/SoilLayer.cpp

####### Install

install:  

uninstall:  

