# This file was autogenerated in base/version_git.sh
struct GitVersionInfo
    commit::String
    commit_short::String
    branch::String
    build_number::Int
    date_string::String
    tagged_commit::Bool
    fork_master_distance::Int
    fork_master_timestamp::Float64
    build_system_commit::String
    build_system_commit_short::String
end

const GIT_VERSION_INFO = GitVersionInfo(
    "742b9abb4dd4621b667ec5bb3434b8b3602f96fd",
    "742b9abb4d",
    "heads/v1.7.3",
    0,
    "2022-05-06 12:58 UTC",
    true,
    508,
    1623241663.,
    "",
    "",
)
