#!/usr/bin/env python

import sys
import os
import argparse
import textwrap
import json

import commentjson


def get_input_paths(config_file="config/config.js", verbose=True):
  '''
  '''
  with open(config_file) as config_fh:
    config = commentjson.load(config_fh)

  #Should this also handle parameter_dir and output_spec file location?
  #At least for now, no. The matching 'set_input_paths' method should likely
  # only apply to this set of files.
  input_filenames = ['hist_climate_file', 'proj_climate_file',
                     'veg_class_file', 'drainage_file', 'soil_texture_file',
                     'co2_file', 'proj_co2_file', 'runmask_file', 'topo_file',
                     'fri_fire_file', 'hist_exp_fire_file',
                     'proj_exp_fire_file']
  if verbose:
    print("Fetching input paths for filenames:", *input_filenames, sep=', ')

  paths = []
  for filename in input_filenames:
#    path = os.path.dirname(config['IO'][filename])
    path = config['IO'][filename]
    if path not in paths:
      paths.append(path)

  return paths


def _parse_config_value(raw_value):
  '''
  Parse a value passed via CLI for writing into config data.
  '''
  try:
    return commentjson.loads(raw_value)
  except ValueError:
    # If it is not valid JSON-like syntax, keep it as a string.
    return raw_value


def set_config_value(config_file, key_path, value, verbose=True):
  '''
  Set a nested configuration value using dot-separated key paths.

  Example key paths:
    IO.output_dir
    stage_settings.eq.env
  '''
  with open(config_file) as config_fh:
    config = commentjson.load(config_fh)

  keys = key_path.split('.')
  if not keys or any(not k for k in keys):
    raise ValueError("Invalid key path: '{}'".format(key_path))

  node = config
  for key in keys[:-1]:
    if key not in node:
      raise KeyError("Missing key in path '{}': '{}'".format(key_path, key))
    if not isinstance(node[key], dict):
      raise TypeError(
          "Cannot descend into non-object key '{}' for path '{}'".format(key, key_path)
      )
    node = node[key]

  if keys[-1] not in node:
    raise KeyError("Target key does not exist: '{}'".format(key_path))

  node[keys[-1]] = value

  with open(config_file, 'w') as config_fh:
    json.dump(config, config_fh, indent=2)
    config_fh.write('\n')

  if verbose:
    print("Updated '{}' in {}".format(key_path, config_file))


def cmdline_define():
  '''Define the command line interface and return the parser object.'''

  parser = argparse.ArgumentParser(
    formatter_class=argparse.RawDescriptionHelpFormatter,
    description=textwrap.dedent('''
      Helper script for a dvm-dos-tem config file.
    ''')
  )
  parser.add_argument('file', nargs='?', metavar=('FILE'),
      help=textwrap.dedent('''The config file to operate on.'''))

  parser.add_argument('--verbose', action='store_true',
      help=textwrap.dedent('''Print info to stdout when script runs.'''))

  parser.add_argument('--get-input-paths', action='store_true',
      help=textwrap.dedent('''Returns all input file paths'''))

  parser.add_argument('--set', nargs=2, action='append', metavar=('KEY_PATH', 'VALUE'),
      help=textwrap.dedent('''Set a config key path to a value. Use dot notation
      for nested keys (e.g. IO.output_dir output/new). VALUE is parsed as JSON if
      possible, otherwise stored as a string.'''))

  return parser

def cmdline_parse(argv=None):
  '''
  The command line interface specification and parser for util config.py.

  If parse_args(...) is called with argv=None, then parse_args(...) will
  use sys.argv[1:]. Otherwise argv is parsed according to the specification.

  Parameters
  ----------
  argv : None or list of strings
    arguments that argparse library will parse; if None, then sys.argv[1:] are
    parsed.

  Returns
  -------
  args : Namespace generated by argparse

  '''
  parser = cmdline_define()

  args = parser.parse_args(argv)

  # print(argv)
  # print(args)

  # Force vebosity on if user requests showing data
  #if args.show:
    #args.verbose = True # ?? Not sure about this...
  
  if (args.file is None) or (not os.path.isfile(args.file)):
    parser.error("'{}' is an invalid path to a config file!".format(args.file))

  return args


def cmdline_run(args):
  '''
  Executes based on the command line arguments.

  Parameters
  ----------
  args : Namespace
    Should be a Namespace with all the appropriate arguments.

  Returns
  -------
  exit_code : int 
    Non-zero if the program cannot complete successfully.

  '''
  if args.get_input_paths:
    get_input_paths(args.file, args.verbose)

  if args.set:
    for key_path, raw_value in args.set:
      value = _parse_config_value(raw_value)
      set_config_value(args.file, key_path, value, verbose=args.verbose)

  return 0


def cmdline_entry(argv=None):
  '''
  Wrapper allowing for easier testing of the cmdline run and parse functions.
  '''
  args = cmdline_parse(argv)
  return cmdline_run(args)


if __name__ == '__main__':
  sys.exit(cmdline_entry()) # this makes sure appropriate exit code is passed on.

